// Mocks generated by Mockito 5.4.6 from annotations
// in squire/test/Acceptance/army_list_acceptance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:squire/data/model/Army_list/Army_unit_data.dart' as _i2;
import 'package:squire/data/repositories/Ability_Repository.dart' as _i5;
import 'package:squire/data/repositories/unit_repository.dart' as _i3;
import 'package:squire/data/services/unit_details_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeListPa_0 extends _i1.SmartFake implements _i2.ListPa {
  _FakeListPa_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UnitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitRepository extends _i1.Mock implements _i3.UnitRepository {
  MockUnitRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ListPa> parseListAndFetchDetails(String? rawArmyListText) =>
      (super.noSuchMethod(
            Invocation.method(#parseListAndFetchDetails, [rawArmyListText]),
            returnValue: _i4.Future<_i2.ListPa>.value(
              _FakeListPa_0(
                this,
                Invocation.method(#parseListAndFetchDetails, [rawArmyListText]),
              ),
            ),
          )
          as _i4.Future<_i2.ListPa>);
}

/// A class which mocks [AbilityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbilityRepository extends _i1.Mock implements _i5.AbilityRepository {
  MockAbilityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> fetchAndCacheAllAbilityEffects() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndCacheAllAbilityEffects, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getAbilityRule(String? rawAbilityName) =>
      (super.noSuchMethod(
            Invocation.method(#getAbilityRule, [rawAbilityName]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getAbilityRule, [rawAbilityName]),
            ),
          )
          as String);
}

/// A class which mocks [UnitDetailsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitDetailsService extends _i1.Mock
    implements _i7.UnitDetailsService {
  MockUnitDetailsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ArmyUnitData>> fetchUnitDetails(
    String? faction,
    List<String>? unitNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUnitDetails, [faction, unitNames]),
            returnValue: _i4.Future<List<_i2.ArmyUnitData>>.value(
              <_i2.ArmyUnitData>[],
            ),
          )
          as _i4.Future<List<_i2.ArmyUnitData>>);
}
